# Generated by Django 6.1.1 on 2026-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("boarding_count", models.IntegerField(default=0)),
                ("alighting_count", models.IntegerField(default=0)),
                ("passengers_inside", models.IntegerField(default=0)),
                ("available_seats", models.IntegerField(default=0)),
                ("is_bus_full", models.BooleanField(default=False)),
            ],
        ),
    ]
