# Generated by Django 6.1.1 on 2026-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bustelemetry",
            old_name="alighting_count",
            new_name="deboarding_count",
        ),
    ]
